[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
verbosity = 2
fuzz = { runs = 1000 }
ffi = true

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 20 }

[profile.lite]
optimizer = false
fuzz = { runs = 10 }
invariant = { runs = 10, depth = 5 }

[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"
sepolia = "https://sepolia.gateway.tenderly.co"
polygon = "https://polygon.llamarpc.com"
arbitrum = "https://arb1.arbitrum.io/rpc"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }